export enum ALL_TECH {
  REACTJS = "reactjs",
  JAVASCRIPT = "javascript",
  TYPESCRIPT = "typescript",
  HTML = "html",
  CSS = "css",
  SASS = "sass",
  BOOTSTRAP = "bootstrap",
  MATERIALUI = "materialui",
  JQUERY = "jquery",
  GIT = "git",
  GITHUB = "github",
  FIREBASE = "firebase",
  NEXTJS = "nextjs",
  REDUX = "redux",
  REDUXTOOLKIT = "reduxtoolkit",
}
