export const ADVANCE_FRONTEND_LIST = [
  {
    title: "Random Color Palette Generator",
    description:
      "Create A Random Color Palette Generator in HTML CSS & JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Easy",
    slug: "random-color-palette-generator",
  },
  {
    title: "TypeWriter Effect",
    description: "Create a Typewriter Effect in ReactJS",
    tags: ["reactjs", "javascript", "css"],
    level: "Medium",
    slug: "typewriter-effect",
  },
  {
    title: "Check Internet Connection",
    description: "Check Offline or Online Status in JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Easy",
    slug: "check-internet-connection",
  },
  {
    title: "Random Password Generator",
    description: "Create A Random Password Generator in HTML CSS & JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Medium",
    slug: "random-password-generator",
  },
  {
    title: "Detect browser or tab close",
    description: "Write a JavaScript function to detect browser or tab close",
    tags: ["javascript", "html", "css"],
    level: "Easy",
    slug: "detect-browser-or-tab-close",
  },
  {
    title: "Convert Text to Speech",
    description: "Convert Text to Speech in JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Hard",
    slug: "convert-text-to-speech",
  },
  {
    title: "Json Formatter",
    description: "Create a Json Formatter in  HTML CSS & JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Easy",
    slug: "json-formatter",
  },
  {
    title: "Download any file",
    description: "Download any file in JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Easy",
    slug: "download-file",
  },
  {
    title: "Take Screenshot",
    description: "Using JavaScript to take a screenshot of the current page",
    tags: ["javascript", "html", "css"],
    level: "Medium",
    slug: "take-screenshot",
  },
  {
    title: "Voice to Text",
    description: "Convert Voice to Text in JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Hard",
    slug: "voice-to-text",
  },
  {
    title: "Record Video",
    description:
      "Javascript WebRTC Project to Record Videos Through Webcam and Display Download Links in HTML5 Table",
    tags: ["javascript", "html", "css"],
    level: "Hard",
    slug: "record-video",
  },
  {
    title: "Extract Text from PDF",
    description: "Extract Text from PDF in JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Medium",
    slug: "extract-text-from-pdf",
  },
  {
    title: "CSV Viewer",
    description: "Create a CSV Viewer in HTML CSS & JavaScript",
    tags: ["javascript", "html", "css"],
    level: "Easy",
    slug: "csv-viewer",
  },
];
